authorisedSystemId:
  name: authorisedSystemId
  in: path
  required: true
  description: "Internal ID (GUID) allocated by the CM when creating an authorised system."
  schema:
    $ref: 'fields.yml#/authorisedSystemId'
billrunId:
  name: billrunId
  in: path
  required: true
  description: "Internal ID (GUID) allocated by the CM when creating a bill run."
  schema:
    $ref: 'fields.yml#/billrunId'
customerFileId:
  name: customerFileId
  in: path
  required: true
  description: "Internal ID (GUID) allocated by the CM when creating a customer file"
  schema:
    $ref: 'fields.yml#/customerFileId'
invoiceId:
  name: invoiceId
  in: path
  required: true
  description: "Internal ID (GUID) allocated by the CM when creating an invoice."
  schema:
    $ref: 'fields.yml#/invoiceId'
licenceId:
  name: licenceId
  in: path
  required: true
  description: "Internal ID (GUID) allocated by the CM when creating a licence."
  schema:
    $ref: 'fields.yml#/licenceId'
rebillBillrunId:
  name: rebillBillrunId
  in: path
  required: true
  description: "Internal ID (GUID) allocated by the CM when creating a bill run. When rebilling this represents the bill run you want to assign the new rebill invoices to."
  schema:
    $ref: 'fields.yml#/billrunId'
rebillInvoiceId:
  name: rebillInvoiceId
  in: path
  required: true
  description: "Internal ID (GUID) allocated by the CM when creating an invoice. When rebilling this represents the invoice you wish to rebill."
  schema:
    $ref: 'fields.yml#/invoiceId'
regime:
  name: regime
  in: path
  required: true
  description: "Charging regime to use"
  schema:
    $ref: 'fields.yml#/slug'
regimeId:
  name: regimeId
  in: path
  required: true
  description: "Internal ID (GUID) allocated by the CM when creating a regime."
  schema:
    $ref: 'fields.yml#/regimeId'
transactionId:
  name: transactionId
  in: path
  required: true
  description: "Internal ID (GUID) allocated by the CM when creating a transaction, not necessarily visible to the user"
  schema:
    $ref: 'fields.yml#/transactionId'
