version: '3.8'

services:
  db:
    image: postgres:10-alpine
    volumes:
      - cha_api_db_volume:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"

  app:
    image: environmentagency/charging-module-api:latest
    ports:
      - "3005:3000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  cha_api_db_volume:
