version: '3.8'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - cma_api_db_volume:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

  app:
    image: environmentagency/sroc-charging-module-api:latest
    ports:
      - "3006:3000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  cma_api_db_volume:
