openapi: 3.0.0
info:
  description: |
    > This `draft` version is intended to facilitate design and development of what will be the first release of Version 2 of the API.

    Provides an interface for calculating charges, creating and queuing transactions, and generating transaction and customer files used to produce Environment Agency invoices.

    This represents Version 2 of the API, which is based on the [sroc-charging-module-api project](https://github.com/DEFRA/sroc-charging-module-api). It is intended to supercede Version 1, which is based on the [charging-module-api project](https://github.com/DEFRA/charging-module-api)

    ## Working with the API

    The [SRoC service team](https://github.com/DEFRA/sroc-service-team) use [Postman](https://www.postman.com/) as the means to interact with the API. Check out their [docs](https://github.com/DEFRA/sroc-service-team/postman) for info on how to go about setting up your own Postman environment.

    ## Build status

    We have grouped the endpoints by build status rather than function. We hope this makes it easier to see what the position for each endpoint is; is it accessible, is it tested, is it relevant.

    As the status of endpoints change the SROC team will make the updated versions of the API available on [Docker Hub](https://hub.docker.com/r/environmentagency/sroc-charging-module-api).

    They will also endeavour to update this spec to match. If unsure about anything, or you see a conflict please contact the team first.

  version: "draft"
  title: Charging Module API V2
  contact:
    name: SROC Service Team
    email: alan.cruikshanks@environment-agency.gov.uk
    url: 'https://github.com/DEFRA/sroc-service-team'
  license:
    name: Open Government Licence (OGL)
    url: 'http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3'
servers:
  - description: Local
    url: 'http://localhost:3003'

tags:
  - name: ready
    description: "Tested by SROC team, and reviewed by WRLS. Ready for formal sign-off phase"
  - name: tested
    description: "Tested by SROC team but awaiting review and feedback from WRLS team"
  - name: available
    description: "Available to start using but has not yet been formally tested by SROC team"
  - name: unavailable
    description: "These will become available eventually but are yet to be fully implemented"
  - name: deprioritised
    description: "These are intended to be delivered but not as MVP"
  - name: suggested
    description: "These could be made available to client systems"
  - name: status
    description: "Used to confirm the status of the service. Available to all and ready to use"
  - name: admin
    description: "Used to administer, monitor, and test the service. Only available when authenticating as an 'admin'"

paths:
  /:
    get:
      operationId: Root
      description: "Confirm service is up and running. Exactly the same as `/status`"
      tags:
        - status
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '../schema/schemas.yml#/status'

  /status:
    $ref: 'paths/status.yml'

  '/admin/regimes':
    $ref: 'paths/admin/regimes.yml'

  '/admin/regimes/{regimeId}':
    $ref: 'paths/admin/regime.yml'

  '/admin/authorised-systems':
    $ref: 'paths/admin/authorised_systems.yml'

  '/admin/authorised-systems/{authorisedSystemId}':
    $ref: 'paths/admin/authorised_system.yml'

  '/admin/health/airbrake':
    $ref: 'paths/admin/health/airbrake.yml'

  '/admin/health/database':
    $ref: 'paths/admin/health/database.yml'

  '/v2/{regime}/bill-runs':
    $ref: 'paths/v2/billruns/bill_runs.yml'

  '/v2/{regime}/bill-runs/{billrunId}':
    $ref: 'paths/v2/billruns/bill_run.yml'

  '/v2/{regime}/bill-runs/{billrunId}/status':
    $ref: 'paths/v2/billruns/bill_run_status.yml'

  '/v2/{regime}/bill-runs/{billrunId}/generate':
    $ref: 'paths/v2/billruns/bill_run_generate.yml'

  '/v2/{regime}/bill-runs/{billrunId}/send':
    $ref: 'paths/v2/billruns/bill_run_send.yml'

  '/v2/{regime}/bill-runs/{billrunId}/invoices/{invoiceId}':
    $ref: 'paths/v2/billruns/invoices/invoice.yml'

  '/v2/{regime}/bill-runs/{billrunId}/licences/{licenceId}':
    $ref: 'paths/v2/billruns/licences/licence.yml'

  '/v2/{regime}/bill-runs/{billrunId}/transactions':
    $ref: 'paths/v2/billruns/transactions/bill_run_transactions.yml'

  '/v2/{regime}/calculate-charge':
    $ref: 'paths/v2/calculate_charge/calculate_charge.yml'

  '/v2/{regime}/transactions':
    $ref: 'paths/v2/transactions/transactions.yml'

  '/v2/{regime}/transactions/{transactionId}':
    $ref: 'paths/v2/transactions/transaction.yml'

security:
  - OAuth2: []

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: "The API uses [AWS Cognito](https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html) to manage authentication and authorisation. To use it you will first need a cognito client ID and password. You then use these to request a bearer token from AWS Cognito. The bearer token is then sent in the `Authorisation` header of your request"
      flows:
        clientCredentials:
          tokenUrl: 'https://chargingmoduleapi.auth.eu-west-1.amazoncognito.com/oauth2/token'
          scopes: {}
